name: ost

services:
  
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "${GATEWAY_PORT:-80}:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app_network
    depends_on:
      web:
        condition: service_healthy
      server:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.entrypoints=https
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.service=nginx-svc
      - traefik.http.services.nginx-svc.loadbalancer.server.port=80
      - traefik.http.services.nginx-svc.loadbalancer.server.scheme=http

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://server:3000}
    restart: unless-stopped
    ports:
      - "${FRONT_PORT:-3000}:3000"
    networks:
      - app_network
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ../../apps/server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - CONNECTION_URI=http://supertokens:3567
      - DATABASE_URL=postgresql://${BUSINESS_DB_USER:-business_user}:${BUSINESS_DB_PASSWORD:-business_password}@postgres:5432/${BUSINESS_DB_NAME:-business}
      - APP_NAME=${APP_NAME:-OST}
      - WEBSITE_DOMAIN=${WEBSITE_DOMAIN:-http://localhost}
      - API_DOMAIN=${API_DOMAIN:-http://localhost}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN:-localhost}
      - SUPERTOKENS_API_KEY=${SUPERTOKENS_API_KEY}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM=${RESEND_FROM}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_ENDPOINT=${R2_ENDPOINT}
      - R2_URL=${R2_URL}
      - GH_TOKEN_OST_PUBLIC=${GH_TOKEN_OST_PUBLIC}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${API_PORT:-4000}:3000"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      # Postgres
      - POSTGRES_DB=${POSTGRES_NAME:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres_password}
      # Business
      - BUSINESS_DB_NAME=${BUSINESS_DB_NAME:-business}
      - BUSINESS_DB_USER=${BUSINESS_DB_USER:-business_user}
      - BUSINESS_DB_PASSWORD=${BUSINESS_DB_PASSWORD:-business_password}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres_user} -d ${POSTGRES_NAME:-postgres} && \
          psql -U ${POSTGRES_USER:-postgres_user} -d ${POSTGRES_NAME:-postgres} -tAc \"SELECT 1 FROM pg_database WHERE datname = '${BUSINESS_DB_NAME:-business}'\" | grep -q 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
