FROM node:22-alpine

# Installation des dépendances de base
RUN apk add --no-cache postgresql-client && \
    corepack enable pnpm

WORKDIR /app

# Copie des fichiers de dépendances et configuration TypeScript
COPY package.json pnpm-lock.yaml* .npmrc* tsconfig.json ./

# Installation des dépendances en mode développement
RUN pnpm install

# Copie du code source
COPY . .

# Génération du client Prisma pour l'environnement de développement
RUN pnpm prisma generate --schema=src/infrastructures/orm/prisma/schema.prisma

# Configuration de l'environnement de développement
ENV NODE_ENV=development
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Exposition du port
EXPOSE 3000
# Exposition du port pour Prisma Studio
EXPOSE 5555

# Commande de démarrage en mode développement
CMD ["pnpm", "run","start:dev"]
