FROM node:22-alpine AS migration

WORKDIR /app
COPY src/persistence/orm/prisma ./schema

CMD ["npx", "--yes", "prisma", "db", "push", "--schema=/app/schema/schema.prisma", "--skip-generate", "&&", "sleep", "infinity"] 


