-- Autoriser les connexions depuis tous les hôtes
CREATE USER ${BUSINESS_DB_USER} WITH PASSWORD '${BUSINESS_DB_PASSWORD}';
ALTER USER ${BUSINESS_DB_USER} WITH SUPERUSER;
CREATE DATABASE ${BUSINESS_DB_NAME};
GRANT ALL PRIVILEGES ON DATABASE ${BUSINESS_DB_NAME} TO ${BUSINESS_DB_USER};

-- Configurer pg_hba.conf dynamiquement
ALTER SYSTEM SET listen_addresses TO '*';
