name: build-server.yml

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  
  tests:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ./apps/server
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node_version: 20
          cache: 'pnpm'
          cache-dependency-path: ./apps/server/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Generate prisma dependencies
        run: pnpm prisma generate --schema=src/persistence/orm/prisma/schema.prisma

      - name: Run unit tests
        run: |
          pnpm run test

  publish:
    needs: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.OST_RELEASE_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=auto
          images: |
            ghcr.io/opensource-together/server
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Upload server artifact
        uses: docker/build-push-action@v6
        with:
          context: ./apps/server
          file: ./apps/server/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
